# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1200, 800)
        Login.setMinimumSize(QtCore.QSize(1200, 800))
        Login.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label_top = QtWidgets.QLabel(self.centralwidget)
        self.label_top.setGeometry(QtCore.QRect(400, 120, 451, 91))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_top.setFont(font)
        self.label_top.setAlignment(QtCore.Qt.AlignCenter)
        self.label_top.setObjectName("label_top")
        self.LoginlineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.LoginlineEdit_username.setGeometry(QtCore.QRect(400, 300, 451, 71))
        self.LoginlineEdit_username.setObjectName("LoginlineEdit_username")
        self.LoginlineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.LoginlineEdit_password.setGeometry(QtCore.QRect(400, 450, 461, 81))
        self.LoginlineEdit_password.setObjectName("LoginlineEdit_password")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(400, 252, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(400, 412, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.LoginpushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.LoginpushButton_login.setGeometry(QtCore.QRect(580, 550, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LoginpushButton_login.setFont(font)
        self.LoginpushButton_login.setObjectName("LoginpushButton_login")
        self.LoginpushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.LoginpushButton_back.setGeometry(QtCore.QRect(400, 550, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LoginpushButton_back.setFont(font)
        self.LoginpushButton_back.setObjectName("LoginpushButton_back")
        self.login_output_label = QtWidgets.QLabel(self.centralwidget)
        self.login_output_label.setGeometry(QtCore.QRect(406, 640, 451, 20))
        self.login_output_label.setText("")
        self.login_output_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_output_label.setObjectName("login_output_label")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label_top.setText(_translate("Login", "Login"))
        self.label_username.setText(_translate("Login", "Username"))
        self.label_password.setText(_translate("Login", "Password"))
        self.LoginpushButton_login.setText(_translate("Login", "Login"))
        self.LoginpushButton_back.setText(_translate("Login", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
