# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_succ.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginSucc(object):
    def setupUi(self, LoginSucc):
        LoginSucc.setObjectName("LoginSucc")
        LoginSucc.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginSucc.sizePolicy().hasHeightForWidth())
        LoginSucc.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(LoginSucc)
        self.centralwidget.setObjectName("centralwidget")
        self.succ_login_label = QtWidgets.QLabel(self.centralwidget)
        self.succ_login_label.setGeometry(QtCore.QRect(210, 680, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.succ_login_label.setFont(font)
        self.succ_login_label.setAlignment(QtCore.Qt.AlignCenter)
        self.succ_login_label.setObjectName("succ_login_label")
        self.cat_image = QtWidgets.QPushButton(self.centralwidget)
        self.cat_image.setGeometry(QtCore.QRect(-6, -9, 1200, 811))
        self.cat_image.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("kitten.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cat_image.setIcon(icon)
        self.cat_image.setIconSize(QtCore.QSize(1200, 800))
        self.cat_image.setCheckable(True)
        self.cat_image.setChecked(False)
        self.cat_image.setObjectName("cat_image")
        self.label_click_me = QtWidgets.QLabel(self.centralwidget)
        self.label_click_me.setGeometry(QtCore.QRect(530, 330, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_click_me.setFont(font)
        self.label_click_me.setObjectName("label_click_me")
        self.cat_image.raise_()
        self.succ_login_label.raise_()
        self.label_click_me.raise_()
        LoginSucc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginSucc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        LoginSucc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginSucc)
        self.statusbar.setObjectName("statusbar")
        LoginSucc.setStatusBar(self.statusbar)

        self.retranslateUi(LoginSucc)
        QtCore.QMetaObject.connectSlotsByName(LoginSucc)

    def retranslateUi(self, LoginSucc):
        _translate = QtCore.QCoreApplication.translate
        LoginSucc.setWindowTitle(_translate("LoginSucc", "MainWindow"))
        self.succ_login_label.setText(_translate("LoginSucc", "Welcome! Thank you for logging in!"))
        self.label_click_me.setText(_translate("LoginSucc", "Click Me!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginSucc = QtWidgets.QMainWindow()
    ui = Ui_LoginSucc()
    ui.setupUi(LoginSucc)
    LoginSucc.show()
    sys.exit(app.exec_())
