# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(1200, 800)
        Register.setMinimumSize(QtCore.QSize(1200, 800))
        Register.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(Register)
        self.centralwidget.setObjectName("centralwidget")
        self.label_top = QtWidgets.QLabel(self.centralwidget)
        self.label_top.setGeometry(QtCore.QRect(520, 120, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_top.setFont(font)
        self.label_top.setObjectName("label_top")
        self.registerLineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.registerLineEdit_username.setGeometry(QtCore.QRect(400, 300, 451, 71))
        self.registerLineEdit_username.setObjectName("registerLineEdit_username")
        self.registerLineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.registerLineEdit_password.setGeometry(QtCore.QRect(400, 450, 461, 81))
        self.registerLineEdit_password.setObjectName("registerLineEdit_password")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(400, 252, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(400, 412, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.RegisterPushButton_register = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterPushButton_register.setGeometry(QtCore.QRect(550, 550, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.RegisterPushButton_register.setFont(font)
        self.RegisterPushButton_register.setObjectName("RegisterPushButton_register")
        self.RegisterPushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterPushButton_back.setGeometry(QtCore.QRect(400, 550, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.RegisterPushButton_back.setFont(font)
        self.RegisterPushButton_back.setObjectName("RegisterPushButton_back")
        self.register_output_label = QtWidgets.QLabel(self.centralwidget)
        self.register_output_label.setGeometry(QtCore.QRect(406, 640, 451, 20))
        self.register_output_label.setText("")
        self.register_output_label.setAlignment(QtCore.Qt.AlignCenter)
        self.register_output_label.setObjectName("register_output_label")
        Register.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Register)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        Register.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Register)
        self.statusbar.setObjectName("statusbar")
        Register.setStatusBar(self.statusbar)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Register"))
        self.label_top.setText(_translate("Register", "Register"))
        self.label_username.setText(_translate("Register", "Username"))
        self.label_password.setText(_translate("Register", "Password"))
        self.RegisterPushButton_register.setText(_translate("Register", "Register"))
        self.RegisterPushButton_back.setText(_translate("Register", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register = QtWidgets.QMainWindow()
    ui = Ui_Register()
    ui.setupUi(Register)
    Register.show()
    sys.exit(app.exec_())
